### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vidyo.vidyoconnector.VideoFrameLayout"

### ISSUE THREAD

**Issue by ruhul015** [Vidyo/helloworld-vidyo.io-android#8]
09-06 00:49:32.802 17571-17571/******** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ********, PID: 17571
    java.lang.RuntimeException: Unable to start activity ComponentInfo{********/********.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class com.vidyo.vidyoconnector.VideoFrameLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2560)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640)
        at android.app.ActivityThread.access$800(ActivityThread.java:182)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5682)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
     Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.vidyo.vidyoconnector.VideoFrameLayout
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.superego.ovvideo.home.MainActivity.onCreate(MainActivity.java:139)
        at android.app.Activity.performCreate(Activity.java:6161)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) 
        at android.app.ActivityThread.access$800(ActivityThread.java:182) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vidyo.vidyoconnector.VideoFrameLayout" on path: DexPathList[[zip file "/data/app/********-1/base.apk"],nativeLibraryDirectories=[/data/app/********-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.view.LayoutInflater.createView(LayoutInflater.java:571)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at ********.MainActivity.onCreate(MainActivity.java:139) 
        at android.app.Activity.performCreate(Activity.java:6161) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2640) 
        at android.app.ActivityThread.access$800(ActivityThread.java:182) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
    	Suppressed: java.lang.ClassNotFoundException: com.vidyo.vidyoconnector.VideoFrameLayout
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 24 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

<img width="362" alt="screen shot 2018-09-06 at 1 12 42 am" src="https://user-images.githubusercontent.com/7602050/45115617-35b14c00-b172-11e8-9030-859ae7fccec4.png">

**Comment by tmelko-vidyo** [comment]
Hi,
There is no such class com.vidyo.vidyoconnector.VideoFrameLayout within this project?
Seems like you copy-paste it from VidyoConnector app comming with SDK package.
It's not a part of SDK.

Please move VideoFrameLayout to your project and if you already did, please make sure that package name **com.vidyo.vidyoconnector** is relevant.
If you place it near MainActivity then change reference in XML to:
<com.example.pfuternik.vidyoiodemo.VideoFrameLayout ... />
